/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    credentials: Credential;
    sessions: Session;
    greetings: Greeting;
    'adk-sessions': AdkSession;
    'session-locks': SessionLock;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    greetings: GreetingsSelect<false> | GreetingsSelect<true>;
    'adk-sessions': AdkSessionsSelect<false> | AdkSessionsSelect<true>;
    'session-locks': SessionLocksSelect<false> | SessionLocksSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 用于登录此管理后台的管理员，不是聊天访客，也不是微信用户账号。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  owner: string;
  digest: string;
  kind: 'cookie' | 'bearer' | 'miniapp';
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 一段聊天对应一份祝福会话。平台、BYOK 和自带 Agent 的产物可归入同一会话；具体输入和回复请看「生成轮次与吉祥话」。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  owner: string;
  title: string;
  memory?: import('./domain/context-policy').Memory | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 每行是一次输入及其生成结果。先对照输入与吉祥话，再检查状态、使用方式和模型；失败轮次也会保留。点击内容查看完整联想依据、会话 ID 和提示词版本。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "greetings".
 */
export interface Greeting {
  id: number;
  owner: string;
  sessionId: number;
  requestKey: string;
  fingerprint: string;
  mode: 'platform' | 'byok' | 'external';
  status: 'running' | 'completed' | 'failed';
  input: import('@cfp/hello-agent-contracts').Inspiration;
  greeting?: string | null;
  association?: string | null;
  model?: string | null;
  promptVersion?: string | null;
  error?: string | null;
  durationMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 内置 ADK 每一轮的执行轨迹，不是用户聊天列表。验收时可检查事件数量和工具调用；外部 Agent 不经过平台 ADK，因此没有对应轨迹。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adk-sessions".
 */
export interface AdkSession {
  id: number;
  owner: string;
  key: string;
  snapshot: import('@google/adk').Session;
  updatedAt: string;
  createdAt: string;
}
/**
 * 防止同一会话并发生成的临时执行锁。正常完成后会释放；异常中断时等待过期。这里不是吉祥话或聊天历史，通常为空。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-locks".
 */
export interface SessionLock {
  id: number;
  owner: string;
  sessionKey: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * 用户发送的图片素材，不是模型生成的图片。列表显示缩略图；图片经过服务端校验、缩放和元信息清理，通过生成轮次中的媒体 ID 关联。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  owner: string;
  mimeType: string;
  base64?: string | null;
  object?: import('./domain/media-policy').ImageReference | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'credentials';
        value: number | Credential;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'greetings';
        value: number | Greeting;
      } | null)
    | ({
        relationTo: 'adk-sessions';
        value: number | AdkSession;
      } | null)
    | ({
        relationTo: 'session-locks';
        value: number | SessionLock;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  owner?: T;
  digest?: T;
  kind?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  owner?: T;
  title?: T;
  memory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "greetings_select".
 */
export interface GreetingsSelect<T extends boolean = true> {
  owner?: T;
  sessionId?: T;
  requestKey?: T;
  fingerprint?: T;
  mode?: T;
  status?: T;
  input?: T;
  greeting?: T;
  association?: T;
  model?: T;
  promptVersion?: T;
  error?: T;
  durationMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adk-sessions_select".
 */
export interface AdkSessionsSelect<T extends boolean = true> {
  owner?: T;
  key?: T;
  snapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-locks_select".
 */
export interface SessionLocksSelect<T extends boolean = true> {
  owner?: T;
  sessionKey?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  owner?: T;
  mimeType?: T;
  base64?: T;
  object?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}