services:
  site:
    image: ${SITE_IMAGE}
    restart: unless-stopped
    env_file:
      - ./.env.production
    ports:
      - "3300:3300"

  miniapp-h5:
    image: ${MINIAPP_H5_IMAGE}
    restart: unless-stopped
    ports:
      - "3301:80"

